name: Deploy to Server

on:
  push:
    branches:
      - master # 這裡使用你的主要分支名稱，可以根據實際情況修改
      - production # 正式站

jobs:
  deploy:
    runs-on: ubuntu-22.04 # ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # 使用官方的Checkout action來檢出你的代碼

      - name: Deploy to Server
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.pem
          chmod 600 ~/.ssh/staging.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Yarn build and start
        if: github.ref == 'refs/heads/master'
        run: ssh staging 'cd /var/www/html/f22 && pm2 stop f22 && git fetch origin && git pull origin master && yarn install && yarn build && pm2 start f22'

      - name: Deploy to AWS EC2
        if: github.ref == 'refs/heads/production'
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${ { secrets.HOST_DNS }}
          REMOTE_USER: ${ { secrets.USERNAME }}
          TARGET: ${ { secrets.TARGET_DIR }}
        with:
          SCRIPT_AFTER: |
            cd /var/www/html/F22-BE && pm2 stop F22-BE && git fetch origin && git pull origin production && yarn install && yarn build && pm2 start F22-BE
