name: Deploy to Server

on:
  push:
    branches:
      - master # 使用您的主要分支名稱

jobs:
  deploy:
    runs-on: ubuntu-22.04 # 或 ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # 檢出代碼

      # 新增安裝 nvm 的步驟
      - name: Install NVM and Node.js
        run: |
          wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
          nvm install 18.17.0
          nvm use 18.17.0

      - name: Deploy to Server
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.pem
          chmod 600 ~/.ssh/staging.pem
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      # 更新此步驟以適應 nvm 的環境
      - name: Yarn build and start
        run: ssh staging '/usr/bin/fish && . $NVM_DIR/nvm.sh && cd /var/www/html/F22-BE && nvm use 18.17.0 && pm2 stop f22 && git fetch origin && git reset --hard origin/master && yarn install && yarn build && pm2 start f22'
